trigger: 
  branches: 
    include: 
      - main 
 
pool: 
  vmImage: 'ubuntu-latest'

steps:
- task: Docker@2 
  inputs: 
    command: 'buildAndPush' 
    repository: 'acrsudheer.azurecr.io/azure-vote' 
    dockerfile: 'Dockerfile' 
    containerRegistry: 'MyACR' 
    tags: 'v$(Build.BuildId)' 